[package]
name = "abyssal"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
figment = { workspace = true, features = ["env", "toml"] }
okapi = { workspace = true, features = ["impl_json_schema", "preserve_order"] }
parking_lot = { workspace = true, features = ["arc_lock", "send_guard", "serde"] }
rocket = { workspace = true, features = ["secrets", "tls", "json", "uuid"] }
rocket_db_pools = { workspace = true }
rocket_okapi = { workspace = true, features = ["preserve_order", "swagger", "uuid", "secrets", "rocket_db_pools", "rocket_ws"] }
rocket_ws = { workspace = true }
schemars = { workspace = true, features = ["preserve_order", "chrono04", "uuid1"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "sqlx-sqlite", "proxy", "runtime-tokio"] }
sea-orm-rocket = { workspace = true, features = ["rocket_okapi"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4", "serde", "fast-rng"] }
